apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - image: barbaralipnik/products:latest
          name: products
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://heffalump.db.elephantsql.com/tnruskwj
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: products-db
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-db
                  key: password
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-server.ingress-nginx.svc.cluster.local:8500
            - name: MICROSERVICE-LOCATIONS_MERCHANTS
              value: http://merchants-service.ingress-nginx.svc.cluster.local:8081
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchants-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchants
  template:
    metadata:
      labels:
        app: merchants
    spec:
      containers:
        - image: barbaralipnik/merchants:latest
          name: merchants
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://heffalump.db.elephantsql.com/xozusiee
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: merchants-db
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: merchants-db
                  key: password
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-server.ingress-nginx.svc.cluster.local:8500
            - name: MICROSERVICE-LOCATIONS_PRODUCTS
              value: http://products-service.ingress-nginx.svc.cluster.local:8080
          ports:
            - containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 3


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - image: barbaralipnik/scraper:latest
          name: scraper
          env:
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-server.ingress-nginx.svc.cluster.local:8500
            - name: MICROSERVICE-LOCATIONS_MERCHANTS
              value: http://merchants-service.ingress-nginx.svc.cluster.local:8081
            - name: MICROSERVICE-LOCATIONS_PRODUCTS
              value: http://products-service.ingress-nginx.svc.cluster.local:8080
            - name: MICROSERVICE-LOCATIONS_EMAILS
              value: http://emails-service.ingress-nginx.svc.cluster.local:8083
          ports:
            - containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 3

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: emails-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emails
  template:
    metadata:
      labels:
        app: emails
    spec:
      containers:
        - image: barbaralipnik/emails:latest
          name: emails
          env:
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-server.ingress-nginx.svc.cluster.local:8500
            - name: MICROSERVICE-LOCATIONS_MERCHANTS
              value: http://merchants-service.ingress-nginx.svc.cluster.local:8081
          ports:
            - containerPort: 8083
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 3



---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: onlygregor/pricecompare-frontend:latest
          name: frontend
          ports:
            - containerPort: 8090
              protocol: TCP




---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - image: swaggerapi/swagger-ui:latest
          name: swagger-ui
          env:
            - name: BASE_URL
              value: /swagger
#            - name: URLS
#              value: "[{url: \"http://merchants-service.ingress-nginx.svc.cluster.local:8081/openapi\", name: \"Merchants\"},{url: \"http://products-service.ingress-nginx.svc.cluster.local:8080/openapi\", name: \"Products\"}]"
            - name: URL
              value: "../merchants/openapi"
          ports:
            - containerPort: 8080
              protocol: TCP









---

apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: products

---

apiVersion: v1
kind: Service
metadata:
  name: merchants-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: merchants

---

apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: scraper

---

apiVersion: v1
kind: Service
metadata:
  name: emails-service
spec:
  type: ClusterIP
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: emails

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: frontend



---

apiVersion: v1
kind: Service
metadata:
  name: swagger-ui-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 8080
  selector:
    app: swagger-ui

