apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - image: barbaralipnik/products:latest
          name: products
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://heffalump.db.elephantsql.com/tnruskwj
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: tnruskwj
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: JIYKCyTt5Kf14ODfZ9fPSddTdwRNHrYi
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      protocol: TCP
      targetPort: server
  selector:
    app: products
