kumuluzee:
  name: products-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    annotations:
      my-resource:
        allow-origin: "*"
  openapi-mp:
    servlet:
      mapping: /products/openapi
    ui:
      server-auto-config:
        enabled: true
        original-uri-check: true
  datasources:
    - jndi-name: jdbc/ProductsDS
      connection-url: jdbc:postgresql://localhost:5433/products
      username: dbuser
      password: postgres
      max-pool-size: 5
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/ProductsDS
        type: liveness
  metrics:
    web-instrumentation:
      - name: products-endpoint
        url-pattern: /v1/products/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
      <Configuration name="comments">
          <Appenders>
              <Console name="console" target="SYSTEM_OUT">
                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
              </Console>
              <Socket name="logstash" host="c01cd245-8af8-4d32-82dc-b9744260a7e6-ls.logit.io"
              port="15190" protocol="udp">
                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
              </Socket>
          </Appenders>
          <Loggers>
              <!-- Default logger -->
              <Root level="info">
                  <AppenderRef ref="console" level="info" />
                  <AppenderRef ref="logstash" level="trace" />
              </Root>
          </Loggers>
      </Configuration>'
  graphql:
    exceptions:
      show-error-message:
        - com.example.exceptions.ShownRuntimeException
  dev:
    scan-libraries:
      - products-services
      - products-models
      - products-lib
rest-properties:
  maintenance-mode: false
  broken: false