kumuluzee:
  name: products-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ProductsDS
      connection-url: jdbc:postgresql://localhost:5433/products
      username: dbuser
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/ProductsDS
        type: liveness
  metrics:
    web-instrumentation:
      - name: products-endpoint
        url-pattern: /v1/products/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
      <Configuration name="comments">
          <Appenders>
              <Console name="console" target="SYSTEM_OUT">
                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
              </Console>
              <Socket name="logstash" host="1be3a1ed-80b7-47f8-8225-24b036ab4bd8-ls.logit.io"
              port="19676" protocol="udp">
                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
              </Socket>
          </Appenders>
          <Loggers>
              <!-- Default logger -->
              <Root level="all">
                  <AppenderRef ref="console" level="info" />
                  <AppenderRef ref="logstash" level="trace" />
              </Root>
          </Loggers>
      </Configuration>'
rest-properties:
  maintenance-mode: false
microservice-locations:
  merchants: http://localhost:8081